version = 1
owned_paths = [
    "app/flow.ron",
    "app/global.fre.ron",
    "app/input.ron",
    "narrative/dialogue.ron",
    "narrative/dialogue.fre.ron",
    "overworld/characters/frisk.character.ron",
    "overworld/characters/frisk/animations.animation_config.ron",
    "overworld/chase_config.ron",
    "overworld/players/player_behavior.ron",
    "overworld/rules/dark_menu.fre.ron",
    "overworld/rules/interaction.fre.ron",
    "overworld/view/dark_menu.view.ron",
    "overworld/view/dialogue.view.ron",
    "view/structures/view_box.sdf.ron",
    "view/touch_layout.ron",
]
